semi: true
printWidth: 150
tabWith: 4
useTabs: false
singleQuote: false
quoteProps: "preserve"
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "avoid"
parser: "typescript"
endOfLine: "auto"